bot-token: "BOTTOKEN"
server-id: "000000000000000000"

staff-list: [ "Dronox", "GreenCreepyGhost", "Cubemaster02", "PokedonGCG", "Cobethel", "EchoEnvoyer", "Anjulah", "Deizhor", "scoutblade", "Cinecs" ]